#!/usr/bin/env bash
# C1/C2/C6: Repository consistency checks.
# Generated by harness-loop skill. Strict mode: strict.
#
# C1: numbers declared in README/AGENTS.md match actual *.md counts.
# C2: subdir paths mentioned in root AGENTS.md each have an AGENTS.md.
# C6: methodology-required subdirs each have an AGENTS.md.

set -uo pipefail

STRICT="strict"
FAILURES=0

# record_failure <check-id> <description> <fix>
record_failure() {
  printf '❌ %s %s\n   修复: %s\n' "$1" "$2" "$3"
  FAILURES=$((FAILURES + 1))
}

# count_md_excluding_agents <dir> — depth-1 *.md count, skipping AGENTS.md.
count_md_excluding_agents() {
  local f n=0
  [[ -d "$1" ]] || { echo 0; return; }
  while IFS= read -r f; do
    [[ "$(basename "$f")" == "AGENTS.md" ]] && continue
    n=$((n + 1))
  done < <(find "$1" -maxdepth 1 -type f -name '*.md' 2>/dev/null)
  echo "$n"
}

# check_number <pattern> <unit-label> <dir-candidates...>
#   Scans $HAYSTACK for the first <pattern> match, extracts the integer,
#   picks the first existing dir from <dir-candidates>, compares counts.
check_number() {
  local pattern="$1" label="$2"; shift 2
  local n target actual
  n=$(printf '%s' "$HAYSTACK" | grep -oiE "$pattern" | head -1 | grep -oE '[0-9]+')
  [[ -z "$n" ]] && return 0
  DECLARATIONS=$((DECLARATIONS + 1))
  target=""
  local d
  for d in "$@"; do [[ -d "$d" ]] && { target="$d"; break; }; done
  [[ -z "$target" ]] && return 0
  actual=$(count_md_excluding_agents "$target")
  if [[ "$actual" -ne "$n" ]]; then
    record_failure "C1" \
      "declared $n $label but $target/ has $actual *.md files" \
      "edit README to match, or add/remove files under $target/ until count = $n"
  fi
}

# ----------------------------------------------------------------------
# C1: number consistency. Heuristic scan of README + root AGENTS.md.
# If no numeric declarations are found, the check is skipped silently.
# ----------------------------------------------------------------------
check_c1() {
  HAYSTACK=""
  local f
  for f in README.md readme.md AGENTS.md; do
    [[ -f "$f" ]] && { HAYSTACK+=$(cat "$f" 2>/dev/null)$'\n'; }
  done
  if [[ -z "$HAYSTACK" ]]; then
    echo "ℹ️  C1 skipped: no README/AGENTS.md to scan"
    return
  fi

  DECLARATIONS=0
  check_number '[0-9]+[ ]?篇'        '篇'         concepts thinking feedback
  check_number '[0-9]+[ ]+articles?' 'articles'   concepts thinking feedback docs
  check_number '[0-9]+[ ]+concepts?' 'concepts'   concepts
  check_number '[0-9]+[ ]+specs?'    'specs'      docs/specs

  [[ "$DECLARATIONS" -eq 0 ]] && \
    echo "ℹ️  C1 skipped: no numeric declarations found in README/AGENTS.md"
}

# ----------------------------------------------------------------------
# C2: subdir paths in root AGENTS.md must each have an AGENTS.md.
# Extracts path-like tokens ending in '/' and verifies each exists.
# ----------------------------------------------------------------------
check_c2() {
  local agents="AGENTS.md"
  if [[ ! -f "$agents" ]]; then
    record_failure "C2" "root AGENTS.md missing" \
      "create AGENTS.md at project root (see templates/agents-root.md.tmpl)"
    return
  fi

  # De-dup path-like tokens (e.g. "src/", "docs/specs/") preserving order.
  local paths=() p existing dup
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    dup=0
    for existing in "${paths[@]+"${paths[@]}"}"; do
      [[ "$existing" == "$p" ]] && { dup=1; break; }
    done
    [[ "$dup" -eq 0 ]] && paths+=("$p")
  done < <(grep -oE '([A-Za-z0-9_.-]+/)+' "$agents" 2>/dev/null)

  if [[ "${#paths[@]}" -eq 0 ]]; then
    echo "ℹ️  C2 skipped: no subdir paths mentioned in AGENTS.md"
    return
  fi

  local trimmed
  for p in "${paths[@]}"; do
    trimmed="${p%/}"
    if [[ -d "$trimmed" ]] && [[ ! -f "$trimmed/AGENTS.md" ]]; then
      record_failure "C2" \
        "$trimmed/ is mentioned in AGENTS.md but has no AGENTS.md" \
        "create $trimmed/AGENTS.md describing the subdir's purpose and rules"
    fi
  done
}

# ----------------------------------------------------------------------
# C6: methodology-required subdirs must each carry an AGENTS.md.
# Reads methodology from state/iteration.md; falls back to common dirs.
# ----------------------------------------------------------------------
check_c6() {
  local methodology=""
  if [[ -f "state/iteration.md" ]]; then
    methodology=$(grep -E '^methodology:' state/iteration.md 2>/dev/null \
      | head -1 | sed -E 's/^methodology:[[:space:]]*//I' | tr -d '[:space:]')
  fi
  local m_lower
  m_lower=$(printf '%s' "$methodology" | tr '[:upper:]' '[:lower:]')

  local expected_dirs
  case "$m_lower" in
    tdd)    expected_dirs=(tests src) ;;
    sdd)    expected_dirs=(docs/specs src) ;;
    bdd)    expected_dirs=(docs/features src) ;;
    ddd)    expected_dirs=(docs/domain src) ;;
    rdd)    expected_dirs=(docs/refactor src) ;;
    hybrid) expected_dirs=(tests docs/specs src) ;;
    plain|"")
      expected_dirs=(tests docs src) ;;
    *)
      echo "ℹ️  C6 unknown methodology '$methodology', falling back to common dirs"
      expected_dirs=(tests docs src) ;;
  esac

  local d
  for d in "${expected_dirs[@]}"; do
    if [[ -d "$d" ]] && [[ ! -f "$d/AGENTS.md" ]]; then
      record_failure "C6" \
        "methodology dir $d/ exists but has no AGENTS.md" \
        "create $d/AGENTS.md (see templates/agents-subdir.md.tmpl)"
    fi
  done
}

# Run all three, then branch on strict mode.
echo "=== C1: number consistency ==="
check_c1
echo
echo "=== C2: subdir references ==="
check_c2
echo
echo "=== C6: methodology-required subdirs ==="
check_c6
echo

if [[ "$FAILURES" -gt 0 ]]; then
  if [[ "$STRICT" == "strict" ]]; then
    echo "🛑 Consistency: $FAILURES failures (strict mode)"
    exit 1
  else
    echo "⚠️  Consistency: $FAILURES failures (advisory mode)"
    exit 0
  fi
fi

echo "✅ Consistency: all checks passed"
exit 0
